CREATE TABLE `fiscal_documents` (
	`id` text PRIMARY KEY NOT NULL,
	`access_key` text NOT NULL,
	`document_number` text NOT NULL,
	`series` text,
	`business_type` text NOT NULL,
	`issue_date` text NOT NULL,
	`party_id` text NOT NULL,
	`issuer_name` text NOT NULL,
	`issuer_document` text,
	`recipient_name` text NOT NULL,
	`recipient_document` text,
	`products_amount_cents` integer DEFAULT 0 NOT NULL,
	`discount_amount_cents` integer DEFAULT 0 NOT NULL,
	`freight_amount_cents` integer DEFAULT 0 NOT NULL,
	`other_amount_cents` integer DEFAULT 0 NOT NULL,
	`total_amount_cents` integer NOT NULL,
	`estimated_kilograms_milli` integer,
	`estimated_price_per_sack_cents` integer,
	`items_json` text NOT NULL,
	`installments_json` text NOT NULL,
	`xml_key` text NOT NULL,
	`original_filename` text,
	`status` text DEFAULT 'PENDING' NOT NULL,
	`deal_id` text,
	`linked_at` text,
	`imported_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`party_id`) REFERENCES `people`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`deal_id`) REFERENCES `deals`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `fiscal_documents_access_key_unique` ON `fiscal_documents` (`access_key`);
