import { NextResponse } from "next/server";
import { apiError } from "@/lib/api-response";
import { bool,cents,d1,id,now,optional } from "@/lib/d1";
import { bankTransactionSchema } from "@/lib/validation";

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){
  try{const transactionId=(await params).id,body=await request.json() as Record<string,unknown>,db=d1();const current=await db.prepare("SELECT t.*,s.id settlement_id,cp.id broker_payment_id,ch.id cheque_id FROM bank_transactions t LEFT JOIN settlements s ON s.bank_transaction_id=t.id LEFT JOIN broker_commission_payments cp ON cp.bank_transaction_id=t.id LEFT JOIN cheques ch ON ch.bank_transaction_id=t.id WHERE t.id=?").bind(transactionId).first<Record<string,unknown>>();if(!current)return NextResponse.json({error:"Movimentação não encontrada."},{status:404});
    if(current.cheque_id)throw new Error("LINKED_TRANSACTION_LOCKED");
    if(body.action==="RECONCILE"){const reconciled=body.reconciled===undefined?Number(current.reconciled):bool(body.reconciled),status=reconciled?"CLEARED":"CONFIRMED",movementDate=optional(body.movementDate)||current.movement_date||current.due_date,stamp=now();await db.batch([db.prepare("UPDATE bank_transactions SET status=?,movement_date=?,reconciled=?,updated_at=? WHERE id=?").bind(status,movementDate,reconciled,stamp,transactionId),db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,before_data,after_data,created_at) VALUES(?,'BankTransaction',?,'RECONCILE',?,?,?)").bind(id(),transactionId,JSON.stringify({status:current.status,reconciled:Boolean(current.reconciled),movementDate:current.movement_date}),JSON.stringify({status,reconciled:Boolean(reconciled),movementDate}),stamp)]);return NextResponse.json({ok:true})}
    if(current.settlement_id||current.broker_payment_id||current.transfer_group_id)throw new Error("LINKED_TRANSACTION_LOCKED");
    const x=bankTransactionSchema.parse(body),movementDate=x.status==="PLANNED"?null:optional(x.movementDate)||x.dueDate,stamp=now();
    if(!await db.prepare("SELECT id FROM bank_accounts WHERE id=? AND active=1").bind(x.bankAccountId).first())throw new Error("BANK_ACCOUNT_NOT_FOUND");
    if(!await db.prepare("SELECT id FROM financial_categories WHERE id=? AND active=1").bind(x.categoryId).first())throw new Error("CATEGORY_NOT_FOUND");
    await db.batch([db.prepare("UPDATE bank_transactions SET bank_account_id=?,direction=?,method=?,status=?,due_date=?,movement_date=?,amount_cents=?,counterparty=?,description=?,document=?,check_number=?,notes=?,financial_category_id=?,reconciled=?,updated_at=? WHERE id=?").bind(x.bankAccountId,x.direction,x.method,x.status,x.dueDate,movementDate,cents(x.amount),x.counterparty,x.description,optional(x.document),optional(x.checkNumber),optional(x.notes),x.categoryId,x.status==="CLEARED"?1:0,stamp,transactionId),db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_data,created_at) VALUES(?,'BankTransaction',?,'UPDATE',?,?)").bind(id(),transactionId,JSON.stringify({amount:x.amount,direction:x.direction,status:x.status}),stamp)]);return NextResponse.json({ok:true})}catch(error){return apiError(error)}
}

export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){
  try{const transactionId=(await params).id,db=d1(),stamp=now();const current=await db.prepare("SELECT t.*,s.id settlement_id,s.origin_type,s.origin_id,s.amount_cents settlement_amount,cp.id broker_payment_id,ch.id cheque_id FROM bank_transactions t LEFT JOIN settlements s ON s.bank_transaction_id=t.id LEFT JOIN broker_commission_payments cp ON cp.bank_transaction_id=t.id LEFT JOIN cheques ch ON ch.bank_transaction_id=t.id WHERE t.id=?").bind(transactionId).first<Record<string,unknown>>();if(!current)return NextResponse.json({error:"Movimentação não encontrada."},{status:404});if(current.cheque_id)throw new Error("LINKED_TRANSACTION_LOCKED");const statements=[];
    statements.push(db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,before_data,after_data,created_at) VALUES(?,'BankTransaction',?,'DELETE',?,?,?)").bind(id(),transactionId,JSON.stringify(current),JSON.stringify({active:false,status:"CANCELLED",recoverable:true}),stamp));
    if(current.settlement_id){const table=current.origin_type==="INSTALLMENT"?"installments":"general_entries";statements.push(db.prepare(`UPDATE ${table} SET paid_amount_cents=MAX(0,paid_amount_cents-?),updated_at=? WHERE id=?`).bind(current.settlement_amount,stamp,current.origin_id),db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,before_data,after_data,created_at) VALUES(?,'Settlement',?,'DELETE',?,?,?)").bind(id(),current.settlement_id,JSON.stringify({id:current.settlement_id,originType:current.origin_type,originId:current.origin_id,amountCents:current.settlement_amount,bankTransactionId:transactionId}),JSON.stringify({recoverable:true}),stamp),db.prepare("DELETE FROM settlements WHERE id=?").bind(current.settlement_id))}
    if(current.broker_payment_id)statements.push(db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,before_data,after_data,created_at) VALUES(?,'BrokerCommissionPayment',?,'DELETE',?,?,?)").bind(id(),current.broker_payment_id,JSON.stringify({id:current.broker_payment_id,bankTransactionId:transactionId}),JSON.stringify({recoverable:true}),stamp),db.prepare("DELETE FROM broker_commission_payments WHERE id=?").bind(current.broker_payment_id));
    if(current.transfer_group_id)statements.push(db.prepare("UPDATE bank_transactions SET active=0,status='CANCELLED',reconciled=0,updated_at=? WHERE transfer_group_id=?").bind(stamp,current.transfer_group_id));else statements.push(db.prepare("UPDATE bank_transactions SET active=0,status='CANCELLED',reconciled=0,updated_at=? WHERE id=?").bind(stamp,transactionId));
    await db.batch(statements);return NextResponse.json({ok:true,deleted:true,recoverable:true})}catch(error){return apiError(error)}
}
