"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, FileCheck2, Landmark, RefreshCw, Tractor } from "lucide-react";
import { MoneyInput } from "@/components/money-input";
import { moneyFromDecimal } from "@/lib/money-input";
import { SettlementModal } from "@/components/settlement-modal";

type Report = {
  competence:string; dueDate:string; generalEntryId:string|null;
  documents:{id:string;documentNumber:string;issueDate:string;producer:string;dealSequence:number|null;status:string;gross:string;rate:number|null;retention:string;net:string}[];
  totals:{documents:number;pendingDocuments:number;gross:string;calculated:string;guide:string|null;difference:string|null;paid:string;balance:string};
  reconciliation:{importedDocumentId:string|null;notes:string;confirmedAt:string|null;status:"WAITING_GUIDE"|"DIFFERENCE"|"CONFIRMED"|"PAID"};
  guides:{id:string;label:string;total:string|null;status:string}[]; accounts:{id:string;bankName:string;accountNumber:string}[];
};
const brDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR");
const brMoney=(value:string|null)=>value==null?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));
const labels={WAITING_GUIDE:"Aguardando guia",DIFFERENCE:"Diferença encontrada",CONFIRMED:"Conferido",PAID:"Pago"};

export function FunruralWorkspace(){
  const[competence,setCompetence]=useState(new Date().toISOString().slice(0,7)),[report,setReport]=useState<Report|null>(null),[guideAmount,setGuideAmount]=useState(""),[guideId,setGuideId]=useState(""),[notes,setNotes]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[settling,setSettling]=useState(false);
  const load=useCallback(async()=>{setBusy(true);setError("");const response=await fetch(`/api/funrural?competencia=${competence}`),body=await response.json();setBusy(false);if(!response.ok){setError(body.error||"Não foi possível carregar o Funrural.");return}setReport(body);setGuideAmount(body.totals.guide==null?"":moneyFromDecimal(body.totals.guide));setGuideId(body.reconciliation.importedDocumentId||"");setNotes(body.reconciliation.notes||"")},[competence]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  async function save(){setBusy(true);setError("");const response=await fetch(`/api/funrural?competencia=${competence}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({guideAmount,importedDocumentId:guideId,notes})}),body=await response.json();setBusy(false);if(!response.ok){setError(body.error||"Não foi possível conferir a guia.");return}setReport(body);setGuideAmount(body.totals.guide==null?"":moneyFromDecimal(body.totals.guide))}
  const status=report?.reconciliation.status||"WAITING_GUIDE",difference=Number(report?.totals.difference||0);
  return <div className="page funrural-page"><header className="records-header"><div><span className="eyebrow">Tributos sobre produtores rurais</span><h1>Conferência mensal do Funrural</h1><p className="page-subtitle">Retenções acumuladas pelos XMLs, comparação com a guia e pagamento no banco — sem misturar os demais tributos do DARF.</p></div><Link className="secondary-button" href="/documentos"><FileCheck2 size={17}/>Importar DARF</Link></header>
  <section className="funrural-toolbar"><label className="field"><span>Competência</span><input type="month" value={competence} onChange={event=>setCompetence(event.target.value)}/></label><button className="secondary-button" disabled={busy} onClick={()=>void load()}><RefreshCw size={16} className={busy?"spin":""}/>Atualizar</button><div className={`funrural-status ${status.toLowerCase()}`}>{status==="DIFFERENCE"?<AlertTriangle/>:<CheckCircle2/>}<span><small>Situação mensal</small><strong>{labels[status]}</strong></span></div></section>
  {error&&<div className="form-error">{error}</div>}{report&&<><section className="funrural-summary"><article><Tractor/><span><small>Compras confirmadas</small><strong>{report.totals.documents} NF-e</strong><em>{brMoney(report.totals.gross)} de base</em></span></article><article><Landmark/><span><small>Retido pelos XMLs</small><strong>{brMoney(report.totals.calculated)}</strong><em>Vence em {brDate(report.dueDate)}</em></span></article><article><FileCheck2/><span><small>Funrural informado na guia</small><strong>{brMoney(report.totals.guide)}</strong><em>O total do DARF não é usado aqui</em></span></article><article className={difference!==0&&report.totals.difference!==null?"attention":""}><CalendarClock/><span><small>Diferença da conferência</small><strong>{brMoney(report.totals.difference)}</strong><em>Pago: {brMoney(report.totals.paid)}</em></span></article></section>
  <div className="funrural-layout"><section className="records-panel funrural-documents"><div className="funrural-section-title"><div><h2>Composição pelos XMLs</h2><p>Somente NF-e vinculada entra no valor mensal. XML pendente aparece para conferência, mas não soma.</p></div><span>{report.totals.pendingDocuments?`${report.totals.pendingDocuments} pendente(s)`:"Tudo vinculado"}</span></div><div className="table-wrap"><table><thead><tr><th>Emissão</th><th>NF-e / negócio</th><th>Produtor</th><th>Valor bruto</th><th>Alíquota</th><th>Retenção</th><th>Valor líquido</th></tr></thead><tbody>{report.documents.map(doc=><tr className={doc.status!=="LINKED"?"funrural-pending":""} key={doc.id}><td>{brDate(doc.issueDate)}</td><td><strong>NF-e {doc.documentNumber}</strong><small>{doc.dealSequence?`Negócio #${String(doc.dealSequence).padStart(5,"0")}`:"Aguardando vínculo"}</small></td><td><strong>{doc.producer}</strong></td><td>{brMoney(doc.gross)}</td><td>{doc.rate==null?"Conferir":`${String(doc.rate).replace(".",",")}%`}</td><td><strong>{brMoney(doc.retention)}</strong></td><td>{brMoney(doc.net)}</td></tr>)}</tbody></table>{!report.documents.length&&<div className="state-box"><Tractor/><strong>Nenhuma compra de produtor nesta competência</strong><p>Ao vincular um XML com retenção, ele aparecerá aqui automaticamente.</p></div>}</div></section>
  <aside className="funrural-reconciliation"><h2>Conferir com o DARF</h2><p>Como um DARF pode trazer vários tributos, informe apenas a parcela correspondente ao Funrural.</p><label className="field"><span>PDF do DARF (opcional)</span><select value={guideId} onChange={event=>setGuideId(event.target.value)}><option value="">Sem PDF vinculado</option>{report.guides.map(guide=><option key={guide.id} value={guide.id}>{guide.label}{guide.total?` · total ${brMoney(guide.total)}`:""}</option>)}</select></label><label className="field"><span>Funrural dentro da guia <b>*</b></span><MoneyInput value={guideAmount} onValueChange={setGuideAmount}/></label><label className="field"><span>Observações</span><textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Ex.: valor confirmado pela contabilidade"/></label><button className="primary-button" disabled={busy||!guideAmount} onClick={save}><CheckCircle2 size={16}/>{busy?"Salvando...":"Salvar e comparar"}</button><div className="funrural-payment"><span><small>Saldo da obrigação</small><strong>{brMoney(report.totals.balance)}</strong></span>{report.generalEntryId&&Number(report.totals.balance)>0?<button className="secondary-button" onClick={()=>setSettling(true)}><Landmark size={16}/>Pagar Funrural</button>:<em>{status==="PAID"?"Obrigação quitada":"A baixa será liberada quando houver retenção vinculada."}</em>}</div></aside></div>
  {settling&&report.generalEntryId&&<SettlementModal origin={{type:"GENERAL_ENTRY",id:report.generalEntryId,label:`Funrural · competência ${competence.slice(5)}/${competence.slice(0,4)}`,remaining:report.totals.balance,direction:"PAYABLE"}} accounts={report.accounts} onClose={()=>setSettling(false)} onSaved={()=>void load()}/>}</>}</div>;
}
