"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";
import { ArrowRight,Boxes,CheckCircle2,Coffee,RefreshCw,Scale,Settings2,TrendingUp,TriangleAlert } from "lucide-react";
import { MoneyInput } from "@/components/money-input";
import { moneyFromDecimal } from "@/lib/money-input";

type Movement={id:string;sequence:number;date:string;party:string;kilograms:string;sacks:string;amount:string};
type Summary={isClosed:boolean;openingKilograms:string;openingSacks:string;openingValue:string;purchaseKilograms:string;purchaseSacks:string;purchaseValue:string;saleKilograms:string;saleSacks:string;saleRevenue:string;averageCostPerSack:string;costOfGoodsSold:string;theoreticalClosingKilograms:string;theoreticalClosingSacks:string;closingKilograms:string;closingSacks:string;closingPricePerSack:string;closingValue:string;physicalAdjustmentKilograms:string;physicalAdjustmentSacks:string;grossProfit:string;generalExpenses:string;commissions:string;operatingResult:string;hasStockCoverage:boolean};
type Data={configured:boolean;beforeStart:boolean;missingClosingMonth:string|null;month:string;setting:{startMonth:string;previousMonth:string;openingKilograms:string;openingSacks:string;openingPricePerSack:string;openingValue:string}|null;summary:Summary|null;purchases:Movement[];sales:Movement[]};
const currentMonth=()=>new Date().toISOString().slice(0,7);
const brl=(value:string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));
const quantity=(kg:string,sacks:string)=>`${Number(sacks).toLocaleString("pt-BR",{maximumFractionDigits:3})} sc · ${Number(kg).toLocaleString("pt-BR",{maximumFractionDigits:3})} kg`;
const date=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR");
const monthLabel=(value:string)=>new Date(`${value}-01T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});

export function InventoryPositionWorkspace(){
 const[month,setMonth]=useState(currentMonth()),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[error,setError]=useState("");
 const[form,setForm]=useState({startMonth:currentMonth(),openingKilograms:"0",openingPricePerSack:"0,00"}),[closingKilograms,setClosingKilograms]=useState(""),[closingPricePerSack,setClosingPricePerSack]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const response=await fetch(`/api/posicao?mes=${month}`),body=await response.json();setLoading(false);if(!response.ok){setError(body.error||"Não foi possível calcular a posição.");return}setData(body);if(body.setting)setForm({startMonth:body.setting.startMonth,openingKilograms:String(body.setting.openingKilograms).replace(".",","),openingPricePerSack:moneyFromDecimal(body.setting.openingPricePerSack)});setClosingKilograms(body.summary?.isClosed?String(body.summary.closingKilograms).replace(".",","):"");setClosingPricePerSack(body.summary?.isClosed?moneyFromDecimal(body.summary.closingPricePerSack):"");if(!body.configured)setSettingsOpen(true)},[month]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function saveSetting(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);setError("");const response=await fetch("/api/posicao",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),body=await response.json();setSaving(false);if(!response.ok){setError(body.error||"Não foi possível salvar o estoque anterior.");return}setSettingsOpen(false);await load()}
 async function saveClosing(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);setError("");const response=await fetch("/api/posicao",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({month,closingKilograms,closingPricePerSack})}),body=await response.json();setSaving(false);if(!response.ok){setError(body.error||"Não foi possível fechar o estoque do mês.");return}await load()}
 const summary=data?.summary;
 return <div className="page inventory-page"><header className="records-header"><div><span className="eyebrow">Inventário físico mensal</span><h1>Posição e resultado do café</h1><p className="page-subtitle">Você informa o estoque final apurado; ele vira automaticamente a abertura do mês seguinte.</p></div><div className="header-buttons"><label className="field month-picker"><small>Mês da apuração</small><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/></label><button className="secondary-button" onClick={()=>setSettingsOpen(!settingsOpen)}><Settings2 size={16}/>Ponto de partida</button></div></header>
 {error&&<div className="form-error">{error}</div>}
 {settingsOpen&&<form className="inventory-settings" onSubmit={saveSetting}><div><span className="eyebrow">Primeira abertura</span><h2>Estoque final do mês anterior</h2><p>Informe quantidade e preço estimado de mercado por saca. Depois, cada fechamento mensal assume automaticamente essa função.</p></div><label className="field"><span>Primeiro mês a calcular <b>*</b></span><input required type="month" value={form.startMonth} onChange={event=>setForm({...form,startMonth:event.target.value})}/></label><label className="field"><span>Quantidade anterior (kg) <b>*</b></span><input required inputMode="decimal" value={form.openingKilograms} onChange={event=>setForm({...form,openingKilograms:event.target.value})}/></label><label className="field"><span>Preço de mercado/saca <b>*</b></span><MoneyInput required value={form.openingPricePerSack} onValueChange={openingPricePerSack=>setForm({...form,openingPricePerSack})}/></label><button className="primary-button" disabled={saving}>{saving?"Salvando...":"Salvar abertura"}</button></form>}
 {loading&&<div className="state-box"><RefreshCw className="spin"/><strong>Recalculando a posição...</strong></div>}
 {!loading&&data?.beforeStart&&<div className="state-box"><TriangleAlert/><strong>Este mês é anterior ao ponto de partida</strong><p>Escolha o primeiro mês configurado ou um mês posterior.</p></div>}
 {!loading&&!data?.configured&&<div className="state-box"><Boxes/><strong>Informe o estoque final anterior</strong><p>Ele será a abertura do primeiro mês calculado.</p></div>}
 {!loading&&data?.missingClosingMonth&&<div className="state-box"><TriangleAlert/><strong>Falta fechar {monthLabel(data.missingClosingMonth)}</strong><p>Informe primeiro o estoque final desse mês. Somente então ele poderá abrir o mês seguinte.</p><button className="primary-button" onClick={()=>setMonth(data.missingClosingMonth!)}>Abrir mês pendente</button></div>}
 {!loading&&summary&&<><form className={`monthly-closing ${summary.isClosed?"closed":""}`} onSubmit={saveClosing}><div>{summary.isClosed?<CheckCircle2/>:<Boxes/>}<span><small>{summary.isClosed?"Mês fechado":"Fechamento necessário"}</small><strong>Estoque final avaliado de {monthLabel(month)}</strong><em>Posição teórica pelos negócios: {quantity(summary.theoreticalClosingKilograms,summary.theoreticalClosingSacks)}</em></span></div><label className="field"><span>Quantidade final (kg) <b>*</b></span><input required inputMode="decimal" value={closingKilograms} onChange={event=>setClosingKilograms(event.target.value)} placeholder="Contagem do mês"/></label><label className="field"><span>Preço estimado por saca <b>*</b></span><MoneyInput required value={closingPricePerSack} onValueChange={setClosingPricePerSack} placeholder="Preço de mercado"/></label><button className="primary-button" disabled={saving}>{saving?"Salvando...":summary.isClosed?"Atualizar fechamento":"Fechar mês"}</button></form>
 <section className="inventory-equation"><article><span>Estoque inicial</span><strong>{quantity(summary.openingKilograms,summary.openingSacks)}</strong><small>{brl(summary.openingValue)}</small></article><b>+</b><article><span>Compras do mês</span><strong>{quantity(summary.purchaseKilograms,summary.purchaseSacks)}</strong><small>{brl(summary.purchaseValue)}</small></article><b>−</b><article><span>Custo do café vendido</span><strong>{brl(summary.costOfGoodsSold)}</strong><small>Vendas: {quantity(summary.saleKilograms,summary.saleSacks)}</small></article><b>=</b><article className="closing"><span>{summary.isClosed?"Estoque final a mercado":"Estoque final teórico"}</span><strong>{quantity(summary.closingKilograms,summary.closingSacks)}</strong><small>{summary.isClosed?`${brl(summary.closingPricePerSack)}/saca · `:""}{brl(summary.closingValue)}</small></article></section>
 {!summary.hasStockCoverage&&<div className="inventory-warning"><TriangleAlert size={18}/><span>O estoque final informado é maior que todo o café disponível ou ficou negativo. Confira o fechamento e as compras.</span></div>}
 {summary.isClosed&&Number(summary.physicalAdjustmentKilograms)!==0&&<div className="inventory-adjustment"><Scale size={17}/><span>Variação física do mês</span><strong>{quantity(summary.physicalAdjustmentKilograms,summary.physicalAdjustmentSacks)}</strong><small>Diferença entre o estoque informado e a posição teórica.</small></div>}
 <section className="inventory-summary"><article><Coffee/><span>Total das compras<strong>{brl(summary.purchaseValue)}</strong><small>{summary.purchaseSacks} sacas</small></span></article><article><TrendingUp/><span>Total das vendas<strong>{brl(summary.saleRevenue)}</strong><small>{summary.saleSacks} sacas</small></span></article><article><Scale/><span>{summary.isClosed?"Preço final de mercado":"Custo médio de referência"}<strong>{brl(summary.isClosed?summary.closingPricePerSack:summary.averageCostPerSack)}</strong><small>Valor por saca</small></span></article><article className="profit"><Boxes/><span>{summary.isClosed?"Lucro bruto a mercado":"Lucro bruto provisório"}<strong>{brl(summary.grossProfit)}</strong><small>{summary.isClosed?"Com estoque avaliado no fechamento":"Será confirmado no fechamento"}</small></span></article></section>
 <section className="result-bridge"><div><span>{summary.isClosed?"Lucro bruto a mercado":"Lucro bruto provisório"}</span><strong>{brl(summary.grossProfit)}</strong></div><ArrowRight/><div><span>Despesas gerais</span><strong>− {brl(summary.generalExpenses)}</strong></div><ArrowRight/><div><span>Comissões</span><strong>− {brl(summary.commissions)}</strong></div><ArrowRight/><div className="net"><span>{summary.isClosed?"Resultado operacional estimado":"Resultado provisório"}</span><strong>{brl(summary.operatingResult)}</strong></div></section>
 <section className="inventory-ledgers"><InventoryTable title="Compras do mês" empty="Nenhuma compra neste mês." rows={data?.purchases??[]}/><InventoryTable title="Vendas do mês" empty="Nenhuma venda neste mês." rows={data?.sales??[]}/></section></>}
 </div>;
}

function InventoryTable({title,empty,rows}:{title:string;empty:string;rows:Movement[]}){return <article className="records-panel"><header><h2>{title}</h2><span>{rows.length} negócio(s)</span></header><div className="table-wrap"><table><thead><tr><th>Nº</th><th>Data</th><th>Fornecedor / cliente</th><th>Quantidade</th><th>Valor</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>#{String(row.sequence).padStart(5,"0")}</td><td>{date(row.date)}</td><td><strong>{row.party}</strong></td><td>{quantity(row.kilograms,row.sacks)}</td><td><strong>{brl(row.amount)}</strong></td></tr>)}</tbody></table>{!rows.length&&<div className="inventory-empty">{empty}</div>}</div></article>}
