"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertCircle, ExternalLink, Printer, RefreshCw } from "lucide-react";
type Option={id:string;legalName:string};
type Row={id:string;sequence:number;date:string;kilograms:string;sacks:string;pricePerSack:string;totalAmount:string;supplier:{legalName:string}};
type Summary={count:number;kilograms:string;sacks:string;amount:string;averagePrice:string};
type Entry={id:string;number:number;amount:string;paidAmount:string;sacks:string|null;pricePerSack:string|null;origin:"CAFE"|"GENERAL";description:string;purchase:{businessType:string;sequence:number;supplier:{legalName:string}}};
type Day={date:string;payable:string;receivable:string;balance:string;cumulative:string;entries:Entry[]};
type BrokerBalance={id:string;name:string;credits:string;paid:string;balance:string};
type BrokerSummary={count:number;credits:string;paid:string;balance:string};
const money=(v:string|number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v));
const date=(v:string)=>new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR");
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`};
const today=()=>new Date().toISOString().slice(0,10);

export function ReportsWorkspace({suppliers,clients}:{suppliers:Option[];clients:Option[]}){
 const[tab,setTab]=useState<"PURCHASE"|"SALE"|"DAILY"|"BROKERS">("DAILY"),[start,setStart]=useState(monthStart()),[end,setEnd]=useState(today()),[person,setPerson]=useState(""),[direction,setDirection]=useState("ALL"),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Summary>({count:0,kilograms:"0",sacks:"0",amount:"0",averagePrice:"0"}),[days,setDays]=useState<Day[]>([]),[brokerRows,setBrokerRows]=useState<BrokerBalance[]>([]),[brokerSummary,setBrokerSummary]=useState<BrokerSummary>({count:0,credits:"0",paid:"0",balance:"0"}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const people=tab==="PURCHASE"?suppliers:tab==="SALE"?clients:[...suppliers,...clients.filter(c=>!suppliers.some(s=>s.id===c.id))];
 const load=useCallback(async()=>{setLoading(true);setError("");try{const common=new URLSearchParams({inicio:start,fim:end});if(person)common.set("pessoa",person);let response:Response;if(tab==="BROKERS"){response=await fetch("/api/relatorios/corretores");const b=await response.json();if(!response.ok)throw new Error(b.error);setBrokerRows(Array.isArray(b.rows)?b.rows:[]);setBrokerSummary(b.summary)}else if(tab==="DAILY"){common.set("direcao",direction);response=await fetch(`/api/relatorios/mapa-diario?${common}`);const b=await response.json();if(!response.ok)throw new Error(b.error);setDays(Array.isArray(b)?b:[])}else{common.set("tipo",tab);response=await fetch(`/api/relatorios/negocios?${common}`);const b=await response.json();if(!response.ok)throw new Error(b.error);setRows(Array.isArray(b.rows)?b.rows:[]);setSummary(b.summary)}}catch(problem){setError(problem instanceof Error&&problem.message?problem.message:"Não foi possível gerar o relatório.")}finally{setLoading(false)}},[tab,start,end,person,direction]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t)},[load]);
 function change(next:typeof tab){setTab(next);setPerson("")}
 const periodTotals=days.reduce((a,d)=>({payable:a.payable+Number(d.payable),receivable:a.receivable+Number(d.receivable)}),{payable:0,receivable:0});
 return <div className="page reports-page">
  <header className="records-header"><div><span className="eyebrow">Conferência e impressão</span><h1>{tab==="DAILY"?"Mapa diário a pagar e receber":tab==="PURCHASE"?"Relatório de compras":tab==="SALE"?"Relatório de vendas":"Saldos dos corretores em aberto"}</h1><p className="page-subtitle">{tab==="BROKERS"?"Conta-corrente sem vencimento, atualizada pelas negociações e pelos pagamentos.":"Café e contas gerais calculados somente no período selecionado."}</p></div><button className="secondary-button print-button" onClick={()=>window.print()}><Printer size={16}/>Imprimir / PDF</button></header>
  <section className="print-report-meta"><div><b>Café BH</b><span>Gestão comercial</span></div><div><b>{tab==="BROKERS"?"Posição atual":`Período: ${date(start)} a ${date(end)}`}</b><span>{person?people.find(item=>item.id===person)?.legalName:"Todos os fornecedores e clientes"}{tab==="DAILY"?` · ${direction==="PAYABLE"?"Somente a pagar":direction==="RECEIVABLE"?"Somente a receber":"Pagar e receber"}`:""}</span></div></section>
  <div className="report-tabs"><button className={tab==="DAILY"?"active":""} onClick={()=>change("DAILY")}>Mapa diário</button><button className={tab==="PURCHASE"?"active":""} onClick={()=>change("PURCHASE")}>Compras</button><button className={tab==="SALE"?"active":""} onClick={()=>change("SALE")}>Vendas</button><button className={tab==="BROKERS"?"active":""} onClick={()=>change("BROKERS")}>Corretores em aberto</button></div>
  {tab!=="BROKERS"&&<section className="report-filters"><label className="field"><span>Data inicial</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field"><span>Data final</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field"><span>{tab==="PURCHASE"?"Fornecedor":tab==="SALE"?"Cliente":"Fornecedor ou cliente"}</span><select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Todos</option>{people.map(p=><option value={p.id} key={p.id}>{p.legalName}</option>)}</select></label>{tab==="DAILY"&&<label className="field"><span>Mostrar</span><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="ALL">Pagar e receber</option><option value="PAYABLE">Somente a pagar</option><option value="RECEIVABLE">Somente a receber</option></select></label>}<button className="secondary-button" disabled={loading||!start||!end} onClick={()=>void load()}><RefreshCw className={loading?"spin":""} size={15}/>{loading?"Gerando...":"Gerar relatório"}</button></section>}
  {error&&<div className="form-error report-error"><AlertCircle size={17}/><span>{error}</span></div>}
  {loading?<div className="state-box report-loading"><RefreshCw className="spin"/><strong>Gerando relatório...</strong></div>:
  tab==="BROKERS"?<><div className="report-totals broker-report-totals"><div><small>Corretores em aberto</small><strong>{brokerSummary.count}</strong></div><div><small>Comissões geradas</small><strong>{money(brokerSummary.credits)}</strong></div><div><small>Total pago</small><strong>{money(brokerSummary.paid)}</strong></div><div className="open-total"><small>Total em aberto</small><strong>{money(brokerSummary.balance)}</strong></div></div><section className="records-panel broker-report"><div className="table-wrap"><table><thead><tr><th>Corretor</th><th>Comissões geradas</th><th>Total pago</th><th>Saldo em aberto</th><th></th></tr></thead><tbody>{brokerRows.map(row=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{money(row.credits)}</td><td>{money(row.paid)}</td><td className="broker-open-balance"><strong>{money(row.balance)}</strong></td><td><Link className="edit-deal" href={`/corretores/ficha?corretor=${row.id}`}>Ver ficha <ExternalLink size={13}/></Link></td></tr>)}</tbody><tfoot><tr><td><strong>Total geral</strong></td><td><strong>{money(brokerSummary.credits)}</strong></td><td><strong>{money(brokerSummary.paid)}</strong></td><td className="broker-open-balance"><strong>{money(brokerSummary.balance)}</strong></td><td></td></tr></tfoot></table>{!brokerRows.length&&<div className="state-box"><strong>Nenhum saldo de corretor em aberto</strong><p>As comissões aparecerão aqui automaticamente quando houver negócios vinculados.</p></div>}</div></section></>:tab!=="DAILY"?<><div className="report-totals"><div><small>Lançamentos</small><strong>{summary.count}</strong></div><div><small>Quilos</small><strong>{Number(summary.kilograms).toLocaleString("pt-BR")}</strong></div><div><small>Sacas</small><strong>{Number(summary.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3})}</strong></div><div><small>Valor total</small><strong>{money(summary.amount)}</strong></div><div><small>Preço médio ponderado</small><strong>{money(summary.averagePrice)}</strong></div></div><section className="records-panel deal-report"><div className="table-wrap"><table><thead><tr><th>Data</th><th>Negócio</th><th>{tab==="PURCHASE"?"Fornecedor":"Cliente"}</th><th>Quilos</th><th>Sacas</th><th>Preço unitário</th><th>Valor total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.date)}</td><td>{String(r.sequence).padStart(5,"0")}</td><td><strong>{r.supplier.legalName}</strong></td><td>{Number(r.kilograms).toLocaleString("pt-BR")}</td><td>{Number(r.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3})}</td><td>{money(r.pricePerSack)}</td><td><strong>{money(r.totalAmount)}</strong></td></tr>)}</tbody></table></div></section></>:
  <section className="daily-map">{days.map(d=><article key={d.date}><div className="daily-date"><strong>{date(d.date)}</strong></div><div className="table-wrap"><table><thead><tr><th>Origem</th><th>Tipo</th><th>Negócio / descrição</th><th>Fornecedor / cliente</th><th>Sacas</th><th>Preço/saca</th><th>Parcela</th><th>Valor em aberto</th></tr></thead><tbody>{d.entries.map(e=><tr key={e.id}><td>{e.origin==="CAFE"?"Café":"Conta geral"}</td><td>{e.purchase.businessType==="PURCHASE"?"A pagar":"A receber"}</td><td>{e.origin==="CAFE"?String(e.purchase.sequence).padStart(5,"0"):e.description}</td><td>{e.purchase.supplier.legalName}</td><td>{e.sacks?Number(e.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3}):"—"}</td><td>{e.pricePerSack?money(e.pricePerSack):"—"}</td><td>{e.origin==="CAFE"?e.number:"—"}</td><td><strong>{money(Number(e.amount)-Number(e.paidAmount))}</strong></td></tr>)}</tbody><tfoot><tr><td colSpan={4}><strong>Total de {date(d.date)}</strong></td><td colSpan={4}><div className="daily-total-values"><span>A pagar<b>{money(d.payable)}</b></span><span>A receber<b>{money(d.receivable)}</b></span><span>Saldo<b>{money(d.balance)}</b></span></div></td></tr></tfoot></table></div></article>)}{days.length>0&&<div className="period-total"><span>Total a pagar <b>{money(periodTotals.payable)}</b></span><span>Total a receber <b>{money(periodTotals.receivable)}</b></span><span>Saldo do período <b>{money(periodTotals.receivable-periodTotals.payable)}</b></span></div>}{!days.length&&!error&&<div className="state-box"><strong>Nenhum vencimento no período</strong><p>Altere as datas ou os filtros para consultar o mapa diário.</p></div>}</section>}
 </div>
}
