"use client";
import { CheckCircle2,Database,Download,HardDriveDownload,History,RefreshCw,ShieldCheck,TriangleAlert } from "lucide-react";
import { useCallback,useEffect,useState } from "react";

type Status={checkedAt:string;counts:{deals:number;bankTransactions:number;fiscalDocuments:number;auditLogs:number};integrity:{ok:boolean;issues:number};backups:{key:string;size:number;uploadedAt:string}[]};
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));
const size=(bytes:number)=>bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;

export function SecurityCenter(){const[status,setStatus]=useState<Status|null>(null),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/seguranca",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error);setStatus(body);setLoading(false)},[]);
 useEffect(()=>{let active=true;fetch("/api/seguranca",{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);if(active){setStatus(body);setLoading(false)}}).catch(()=>{if(active){setMessage("Não foi possível conferir a proteção agora.");setLoading(false)}});return()=>{active=false}},[]);
 async function backup(){setCreating(true);setMessage("");try{const response=await fetch("/api/seguranca",{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error);setMessage(`Backup concluído: ${body.records} registros e ${body.files} arquivos catalogados.`);await load()}catch{setMessage("Não foi possível criar o backup.")}finally{setCreating(false)}}
 return <div className="page"><header className="page-header"><div><span className="eyebrow">Proteção e recuperação</span><h1>Segurança dos dados</h1><p className="page-subtitle">Integridade, histórico e cópias recuperáveis do Sistema Café.</p></div><button className="primary-button" onClick={backup} disabled={creating}><HardDriveDownload size={18}/>{creating?"Criando backup…":"Criar backup agora"}</button></header>
 {message&&<div className="notice-banner">{message}</div>}
 <section className="summary-grid security-summary"><article className="summary-card"><ShieldCheck size={23}/><span>Integridade atual</span><strong>{loading?"Conferindo…":status?.integrity.ok?"Tudo certo":`${status?.integrity.issues} pendência(s)`}</strong><small>{status?.integrity.ok?"Nenhum vínculo quebrado encontrado":"Requer revisão antes de continuar"}</small></article><article className="summary-card"><Database size={23}/><span>Dados operacionais</span><strong>{status?status.counts.deals+status.counts.bankTransactions+status.counts.fiscalDocuments:"—"}</strong><small>Negócios, banco e documentos fiscais ativos</small></article><article className="summary-card"><History size={23}/><span>Histórico de auditoria</span><strong>{status?.counts.auditLogs??"—"}</strong><small>Alterações preservadas</small></article><article className="summary-card"><HardDriveDownload size={23}/><span>Último backup</span><strong>{status?.backups[0]?date(status.backups[0].uploadedAt):"Ainda não criado"}</strong><small>Cópia separada no armazenamento privado</small></article></section>
 <section className="table-card security-card"><div className="section-heading"><div><span className="eyebrow">Cópias disponíveis</span><h2>Histórico de backups</h2></div><button className="secondary-button" onClick={()=>load()} disabled={loading}><RefreshCw size={16}/>Atualizar</button></div>{status?.backups.length?<div className="security-backups">{status.backups.map(item=><div key={item.key}><span className="security-file-icon"><CheckCircle2 size={18}/></span><span><strong>{date(item.uploadedAt)}</strong><small>{size(item.size)} · banco completo e relação dos documentos</small></span><a className="secondary-button" href={`/api/seguranca?download=${encodeURIComponent(item.key)}`}><Download size={16}/>Baixar</a></div>)}</div>:<div className="empty-state"><TriangleAlert size={24}/><strong>Nenhum backup próprio disponível.</strong><span>Use “Criar backup agora” para gerar a primeira cópia.</span></div>}</section>
 <div className="security-note"><ShieldCheck size={18}/><span><strong>Proteção automática:</strong> ao usar o aplicativo, o sistema solicita no máximo um backup por dia. Exclusões operacionais agora preservam o histórico para recuperação técnica.</span></div></div>}
