import { d1, money } from "@/lib/d1";
const iso=(date:Date)=>date.toISOString().slice(0,10); const addDays=(date:string,days:number)=>{const copy=new Date(`${date}T12:00:00`);copy.setDate(copy.getDate()+days);return iso(copy)};
type Entry={direction:"IN"|"OUT";amount:string;bankName:string;accountNumber:string;counterparty:string;description:string;status:string;category:string;origin:string};

export async function cashFlow(start?:string|null,end?:string|null,accountId?:string|null){
 const from=start||iso(new Date()),to=end||addDays(from,30),db=d1(),filter=accountId??null;
 const opening=await db.prepare(`SELECT COALESCE((SELECT SUM(a.opening_balance_cents) FROM bank_accounts a WHERE a.active=1 AND (? IS NULL OR a.id=?)),0)+COALESCE((SELECT SUM(CASE WHEN t.direction='IN' THEN t.amount_cents ELSE -t.amount_cents END) FROM bank_transactions t JOIN bank_accounts a ON a.id=t.bank_account_id WHERE a.active=1 AND t.active=1 AND t.status IN ('CONFIRMED','CLEARED') AND COALESCE(t.movement_date,t.due_date)<? AND (? IS NULL OR t.bank_account_id=?)),0) amount`).bind(filter,filter,from,filter,filter).first<{amount:number}>();
 const bank=await db.prepare(`SELECT CASE WHEN t.status IN ('CONFIRMED','CLEARED') THEN COALESCE(t.movement_date,t.due_date) ELSE t.due_date END date,t.direction,t.amount_cents,a.bank_name,a.account_number,t.counterparty,t.description,t.status,COALESCE(c.name,CASE WHEN t.method='TRANSFER' THEN 'Transferência entre contas' ELSE 'Sem categoria' END) category FROM bank_transactions t JOIN bank_accounts a ON a.id=t.bank_account_id LEFT JOIN financial_categories c ON c.id=t.financial_category_id WHERE t.active=1 AND t.status<>'CANCELLED' AND (CASE WHEN t.status IN ('CONFIRMED','CLEARED') THEN COALESCE(t.movement_date,t.due_date) ELSE t.due_date END) BETWEEN ? AND ? AND (? IS NULL OR t.bank_account_id=?) ORDER BY date,t.created_at`).bind(from,to,filter,filter).all();
 const pending=filter?{results:[] as Record<string,unknown>[]} : await db.prepare(`SELECT i.due_date date,CASE WHEN d.business_type='PURCHASE' THEN 'OUT' ELSE 'IN' END direction,(i.amount_cents-i.paid_amount_cents) amount_cents,p.legal_name counterparty,'Negócio de café #' || printf('%05d',d.sequence) description,CASE WHEN d.business_type='PURCHASE' THEN 'Compra de café' ELSE 'Venda de café' END category,'Parcela em aberto' origin FROM installments i JOIN deals d ON d.id=i.deal_id JOIN people p ON p.id=d.party_id WHERE d.status='OPEN' AND i.amount_cents>i.paid_amount_cents AND i.due_date BETWEEN ? AND ? UNION ALL SELECT g.due_date date,CASE WHEN g.direction='PAYABLE' THEN 'OUT' ELSE 'IN' END direction,(g.amount_cents-g.paid_amount_cents) amount_cents,COALESCE(p.legal_name,'Sem pessoa vinculada') counterparty,g.description description,c.name category,'Conta geral em aberto' origin FROM general_entries g JOIN financial_categories c ON c.id=g.category_id LEFT JOIN people p ON p.id=g.person_id WHERE g.active=1 AND g.amount_cents>g.paid_amount_cents AND g.due_date BETWEEN ? AND ? ORDER BY date`).bind(from,to,from,to).all();
 const byDate=new Map<string,{in:number;out:number;entries:Entry[]}>(); const push=(row:Record<string,unknown>,origin:string)=>{const key=String(row.date),day=byDate.get(key)??{in:0,out:0,entries:[]},amount=Number(row.amount_cents),direction=row.direction as "IN"|"OUT";if(direction==='IN')day.in+=amount;else day.out+=amount;day.entries.push({direction,amount:money(amount),bankName:String(row.bank_name??"—"),accountNumber:String(row.account_number??""),counterparty:String(row.counterparty),description:String(row.description),status:String(row.status??"PREVISTO"),category:String(row.category),origin});byDate.set(key,day)};
 bank.results.forEach(row=>push(row,"Movimentação bancária")); pending.results.forEach(row=>push(row,String(row.origin)));
 let balance=Number(opening?.amount??0); const days=[] as {date:string;opening:string;incoming:string;outgoing:string;closing:string;entries:Entry[]}[];for(let current=from;current<=to;current=addDays(current,1)){const data=byDate.get(current)??{in:0,out:0,entries:[]};const initial=balance;balance+=data.in-data.out;days.push({date:current,opening:money(initial),incoming:money(data.in),outgoing:money(data.out),closing:money(balance),entries:data.entries})}
 const accounts=await db.prepare("SELECT id,bank_name bankName,account_number accountNumber FROM bank_accounts WHERE active=1 ORDER BY bank_name,account_number").all();return{from,to,opening:money(Number(opening?.amount??0)),accounts:accounts.results,days};
}
