import { cents,d1,id,money,now,optional } from "@/lib/d1";
import { chequeActionSchema,chequeBatchSchema } from "@/lib/validation";

type OriginType="INSTALLMENT"|"GENERAL_ENTRY";
type Origin={type:OriginType;id:string};

const chequeRecord=(row:Record<string,unknown>)=>({id:String(row.id),bankName:String(row.bank_name),agency:row.agency?String(row.agency):null,accountNumber:row.account_number?String(row.account_number):null,checkNumber:String(row.check_number),issuerName:String(row.issuer_name),amount:money(Number(row.amount_cents)),receivedAt:String(row.received_at),dueDate:String(row.due_date),status:String(row.status),ocrConfidence:row.ocr_confidence==null?null:Number(row.ocr_confidence),hasImage:Boolean(row.image_key),notes:row.notes?String(row.notes):null,receivedFrom:row.received_from_name?{id:String(row.received_from_person_id),name:String(row.received_from_name)}:null,depositAccount:row.deposit_bank_name?{id:String(row.deposit_bank_account_id),name:String(row.deposit_bank_name),number:String(row.deposit_account_number)}:null,transferredTo:row.transferred_to_name?{id:String(row.transferred_to_person_id),name:String(row.transferred_to_name)}:null});

async function findOrigin(origin:Origin){
  const db=d1();
  if(origin.type==="INSTALLMENT")return db.prepare("SELECT i.id,i.amount_cents,i.paid_amount_cents,d.business_type,p.legal_name,'Negócio #' || printf('%05d',d.sequence) label FROM installments i JOIN deals d ON d.id=i.deal_id JOIN people p ON p.id=d.party_id WHERE i.id=? AND d.status='OPEN'").bind(origin.id).first<Record<string,unknown>>();
  return db.prepare("SELECT g.id,g.amount_cents,g.paid_amount_cents,g.direction business_type,COALESCE(p.legal_name,'Sem pessoa') legal_name,g.description label FROM general_entries g LEFT JOIN people p ON p.id=g.person_id WHERE g.id=? AND g.active=1").bind(origin.id).first<Record<string,unknown>>();
}
const originTable=(type:OriginType)=>type==="INSTALLMENT"?"installments":"general_entries";
const isReceivable=(type:OriginType,row:Record<string,unknown>)=>type==="INSTALLMENT"?row.business_type==="SALE":row.business_type==="RECEIVABLE";
const isPayable=(type:OriginType,row:Record<string,unknown>)=>type==="INSTALLMENT"?row.business_type==="PURCHASE":row.business_type==="PAYABLE";

export async function chequeOptions(){
  const db=d1(),[people,accounts,installments,general]=await Promise.all([
    db.prepare("SELECT id,legal_name name FROM people WHERE active=1 ORDER BY legal_name").all(),
    db.prepare("SELECT id,bank_name bankName,account_number accountNumber FROM bank_accounts WHERE active=1 ORDER BY bank_name,account_number").all(),
    db.prepare("SELECT i.id,'INSTALLMENT' type,d.business_type direction,'Negócio #' || printf('%05d',d.sequence) || ' · ' || p.legal_name label,(i.amount_cents-i.paid_amount_cents) remaining_cents FROM installments i JOIN deals d ON d.id=i.deal_id JOIN people p ON p.id=d.party_id WHERE d.status='OPEN' AND i.amount_cents>i.paid_amount_cents ORDER BY i.due_date").all(),
    db.prepare("SELECT g.id,'GENERAL_ENTRY' type,g.direction,g.description || ' · ' || COALESCE(p.legal_name,'Sem pessoa') label,(g.amount_cents-g.paid_amount_cents) remaining_cents FROM general_entries g LEFT JOIN people p ON p.id=g.person_id WHERE g.active=1 AND g.amount_cents>g.paid_amount_cents ORDER BY g.due_date").all(),
  ]);
  const origins=[...installments.results,...general.results].map(row=>({id:String(row.id),type:String(row.type),direction:String(row.direction)==="SALE"||String(row.direction)==="RECEIVABLE"?"RECEIVABLE":"PAYABLE",label:String(row.label),remaining:money(Number(row.remaining_cents))}));
  return{people:people.results,accounts:accounts.results,receivables:origins.filter(x=>x.direction==="RECEIVABLE"),payables:origins.filter(x=>x.direction==="PAYABLE")};
}

export async function listCheques(search="",status=""){
  const db=d1(),query=`%${search}%`,result=await db.prepare(`SELECT c.*,p.legal_name received_from_name,ba.id deposit_bank_account_id,ba.bank_name deposit_bank_name,ba.account_number deposit_account_number,tp.id transferred_to_person_id,tp.legal_name transferred_to_name
    FROM cheques c LEFT JOIN cheque_batches b ON b.id=c.batch_id LEFT JOIN people p ON p.id=b.received_from_person_id LEFT JOIN bank_transactions bt ON bt.id=c.bank_transaction_id LEFT JOIN bank_accounts ba ON ba.id=bt.bank_account_id LEFT JOIN people tp ON tp.id=(SELECT person_id FROM cheque_events WHERE cheque_id=c.id AND event_type='TRANSFERRED' ORDER BY created_at DESC LIMIT 1)
    WHERE c.active=1 AND (?='' OR c.status=?) AND (c.issuer_name LIKE ? OR c.bank_name LIKE ? OR c.check_number LIKE ? OR COALESCE(p.legal_name,'') LIKE ?) ORDER BY c.due_date,c.created_at`).bind(status,status,query,query,query,query).all();
  const totals=result.results.reduce((sum,row)=>{const amount=Number(row.amount_cents);sum.total+=amount;if(row.status==="IN_PORTFOLIO"||row.status==="POSTDATED")sum.portfolio+=amount;if(row.status==="DEPOSITED")sum.deposited+=amount;if(row.status==="RETURNED")sum.returned+=amount;return sum},{total:0,portfolio:0,deposited:0,returned:0});
  return{rows:result.results.map(chequeRecord),summary:{count:result.results.length,total:money(totals.total),portfolio:money(totals.portfolio),deposited:money(totals.deposited),returned:money(totals.returned)}};
}

export async function createChequeBatch(input:unknown){
  const data=chequeBatchSchema.parse(input),db=d1(),stamp=now(),batchId=id(),origin=data.receiptOrigin??null,totalCents=data.cheques.reduce((sum,row)=>sum+cents(row.amount),0);
  const found=await Promise.all(data.cheques.map(row=>db.prepare("SELECT id FROM cheques WHERE operation_key=?").bind(row.operationKey).first<{id:string}>()));
  if(found.every(Boolean))return{batchId,created:0,duplicate:true};if(found.some(Boolean))throw new Error("PARTIAL_CHEQUE_BATCH");
  let originRow:Record<string,unknown>|null=null;
  if(origin){originRow=await findOrigin(origin);if(!originRow||!isReceivable(origin.type,originRow))throw new Error("CHEQUE_RECEIVABLE_INVALID");if(totalCents>Number(originRow.amount_cents)-Number(originRow.paid_amount_cents))throw new Error("SETTLEMENT_EXCEEDS_BALANCE")}
  if(data.receivedFromPersonId){const person=await db.prepare("SELECT id FROM people WHERE id=? AND active=1").bind(data.receivedFromPersonId).first();if(!person)throw new Error("ORIGIN_NOT_FOUND")}
  const statements=[db.prepare("INSERT INTO cheque_batches(id,received_from_person_id,received_at,notes,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(batchId,optional(data.receivedFromPersonId),data.receivedAt,optional(data.notes),stamp,stamp)];
  for(const row of data.cheques){const chequeId=id(),amountCents=cents(row.amount),status=row.dueDate>stamp.slice(0,10)?"POSTDATED":"IN_PORTFOLIO";statements.push(db.prepare("INSERT INTO cheques(id,batch_id,operation_key,bank_name,agency,account_number,check_number,issuer_name,amount_cents,received_at,due_date,status,image_key,ocr_confidence,receipt_origin_type,receipt_origin_id,notes,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)").bind(chequeId,batchId,row.operationKey,row.bankName,optional(row.agency),optional(row.accountNumber),row.checkNumber,row.issuerName,amountCents,data.receivedAt,row.dueDate,status,optional(row.imageKey),row.ocrConfidence??null,origin?.type??null,origin?.id??null,optional(row.notes),stamp,stamp));if(origin)statements.push(db.prepare(`UPDATE ${originTable(origin.type)} SET paid_amount_cents=paid_amount_cents+?,updated_at=? WHERE id=?`).bind(amountCents,stamp,origin.id));statements.push(db.prepare("INSERT INTO cheque_events(id,cheque_id,event_type,event_date,person_id,notes,created_at,updated_at) VALUES(?,?,'RECEIVED',?,?,?,?,?)").bind(id(),chequeId,data.receivedAt,optional(data.receivedFromPersonId),optional(data.notes),stamp,stamp))}
  statements.push(db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_data,created_at) VALUES(?,'ChequeBatch',?,'CREATE',?,?)").bind(id(),batchId,JSON.stringify({count:data.cheques.length,total:money(totalCents),receiptOrigin:origin}),stamp));
  await db.batch(statements);return{batchId,created:data.cheques.length,total:money(totalCents)};
}

export async function chequeHistory(chequeId:string){const db=d1(),cheque=await db.prepare("SELECT * FROM cheques WHERE id=?").bind(chequeId).first<Record<string,unknown>>();if(!cheque)throw new Error("CHEQUE_NOT_FOUND");const events=await db.prepare("SELECT e.*,ba.bank_name,ba.account_number,p.legal_name FROM cheque_events e LEFT JOIN bank_accounts ba ON ba.id=e.bank_account_id LEFT JOIN people p ON p.id=e.person_id WHERE e.cheque_id=? ORDER BY e.created_at DESC").bind(chequeId).all();return{cheque:chequeRecord(cheque),events:events.results.map(row=>({id:String(row.id),type:String(row.event_type),date:String(row.event_date),bank:row.bank_name?`${row.bank_name} · ${row.account_number}`:null,person:row.legal_name?String(row.legal_name):null,notes:row.notes?String(row.notes):null}))}}

export async function actOnCheque(chequeId:string,input:unknown){
  const action=chequeActionSchema.parse(input),db=d1(),stamp=now(),cheque=await db.prepare("SELECT * FROM cheques WHERE id=? AND active=1").bind(chequeId).first<Record<string,unknown>>();if(!cheque)throw new Error("CHEQUE_NOT_FOUND");const current=String(cheque.status),amountCents=Number(cheque.amount_cents),statements=[];
  const event=(type:string,bankAccountId?:string|null,personId?:string|null)=>db.prepare("INSERT INTO cheque_events(id,cheque_id,event_type,event_date,bank_account_id,person_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),chequeId,type,action.date,bankAccountId??null,personId??null,optional(action.notes),stamp,stamp);
  if(action.action==="DEPOSIT"){
    if(!["IN_PORTFOLIO","POSTDATED"].includes(current))throw new Error("CHEQUE_STATUS_INVALID");const account=await db.prepare("SELECT id FROM bank_accounts WHERE id=? AND active=1").bind(action.bankAccountId).first();if(!account)throw new Error("BANK_ACCOUNT_NOT_FOUND");const transactionId=id();statements.push(db.prepare("INSERT INTO bank_transactions(id,bank_account_id,direction,method,status,due_date,movement_date,amount_cents,counterparty,description,document,check_number,reconciled,notes,operation_key,active,created_at,updated_at) VALUES(?,?,'IN','CHECK','PLANNED',?,NULL,?,?,?,NULL,?,0,?,?,1,?,?)").bind(transactionId,action.bankAccountId,action.date,amountCents,String(cheque.issuer_name),`Depósito de cheque #${String(cheque.check_number)}`,String(cheque.check_number),optional(action.notes),`cheque:${chequeId}:deposit`,stamp,stamp),db.prepare("UPDATE cheques SET status='DEPOSITED',bank_transaction_id=?,updated_at=? WHERE id=?").bind(transactionId,stamp,chequeId),event("DEPOSITED",action.bankAccountId));
  }else if(action.action==="CLEAR"){
    if(current!=="DEPOSITED"||!cheque.bank_transaction_id)throw new Error("CHEQUE_STATUS_INVALID");statements.push(db.prepare("UPDATE bank_transactions SET status='CLEARED',movement_date=?,reconciled=1,updated_at=? WHERE id=?").bind(action.date,stamp,cheque.bank_transaction_id),db.prepare("UPDATE cheques SET status='CLEARED',updated_at=? WHERE id=?").bind(stamp,chequeId),event("CLEARED"));
  }else if(action.action==="TRANSFER"){
    if(!["IN_PORTFOLIO","POSTDATED"].includes(current))throw new Error("CHEQUE_STATUS_INVALID");if(!action.origin)throw new Error("CHEQUE_PAYABLE_INVALID");const origin=await findOrigin(action.origin);if(!origin||!isPayable(action.origin.type,origin))throw new Error("CHEQUE_PAYABLE_INVALID");if(amountCents>Number(origin.amount_cents)-Number(origin.paid_amount_cents))throw new Error("SETTLEMENT_EXCEEDS_BALANCE");const person=await db.prepare("SELECT id FROM people WHERE id=? AND active=1").bind(action.personId).first();if(!person)throw new Error("ORIGIN_NOT_FOUND");statements.push(db.prepare(`UPDATE ${originTable(action.origin.type)} SET paid_amount_cents=paid_amount_cents+?,updated_at=? WHERE id=?`).bind(amountCents,stamp,action.origin.id),db.prepare("UPDATE cheques SET status='TRANSFERRED',transfer_origin_type=?,transfer_origin_id=?,updated_at=? WHERE id=?").bind(action.origin.type,action.origin.id,stamp,chequeId),event("TRANSFERRED",null,action.personId));
  }else if(action.action==="RETURN"){
    if(!["DEPOSITED","CLEARED","TRANSFERRED"].includes(current))throw new Error("CHEQUE_STATUS_INVALID");if(cheque.bank_transaction_id)statements.push(db.prepare("UPDATE bank_transactions SET status='CANCELLED',reconciled=0,updated_at=? WHERE id=?").bind(stamp,cheque.bank_transaction_id));if(cheque.receipt_origin_type&&cheque.receipt_origin_id)statements.push(db.prepare(`UPDATE ${originTable(String(cheque.receipt_origin_type) as OriginType)} SET paid_amount_cents=MAX(0,paid_amount_cents-?),updated_at=? WHERE id=?`).bind(amountCents,stamp,cheque.receipt_origin_id));if(cheque.transfer_origin_type&&cheque.transfer_origin_id)statements.push(db.prepare(`UPDATE ${originTable(String(cheque.transfer_origin_type) as OriginType)} SET paid_amount_cents=MAX(0,paid_amount_cents-?),updated_at=? WHERE id=?`).bind(amountCents,stamp,cheque.transfer_origin_id));statements.push(db.prepare("UPDATE cheques SET status='RETURNED',updated_at=? WHERE id=?").bind(stamp,chequeId),event("RETURNED"));
  }else if(action.action==="RECOVER"){
    if(current!=="RETURNED")throw new Error("CHEQUE_STATUS_INVALID");if(cheque.receipt_origin_type&&cheque.receipt_origin_id)statements.push(db.prepare(`UPDATE ${originTable(String(cheque.receipt_origin_type) as OriginType)} SET paid_amount_cents=paid_amount_cents+?,updated_at=? WHERE id=?`).bind(amountCents,stamp,cheque.receipt_origin_id));const status=String(cheque.due_date)>action.date?"POSTDATED":"IN_PORTFOLIO";statements.push(db.prepare("UPDATE cheques SET status=?,bank_transaction_id=NULL,transfer_origin_type=NULL,transfer_origin_id=NULL,updated_at=? WHERE id=?").bind(status,stamp,chequeId),event("RECOVERED"));
  }else if(action.action==="CANCEL"){
    if(!["IN_PORTFOLIO","POSTDATED"].includes(current))throw new Error("CHEQUE_STATUS_INVALID");if(cheque.receipt_origin_type&&cheque.receipt_origin_id)statements.push(db.prepare(`UPDATE ${originTable(String(cheque.receipt_origin_type) as OriginType)} SET paid_amount_cents=MAX(0,paid_amount_cents-?),updated_at=? WHERE id=?`).bind(amountCents,stamp,cheque.receipt_origin_id));statements.push(db.prepare("UPDATE cheques SET status='CANCELLED',updated_at=? WHERE id=?").bind(stamp,chequeId),event("CANCELLED"));
  }
  statements.push(db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_data,created_at) VALUES(?,'Cheque',?,?,?,?)").bind(id(),chequeId,action.action,JSON.stringify(action),stamp));await db.batch(statements);return{ok:true};
}
