import { bool, cents, d1, id, money, now, optional } from "@/lib/d1";
import { generalEntrySchema } from "@/lib/validation";
import { monthlyDueDates } from "@/lib/financial-rules";

const record=(entry:Record<string,unknown>)=>({id:entry.id,direction:entry.direction,description:entry.description,dueDate:entry.due_date,amount:money(Number(entry.amount_cents)),paidAmount:money(Number(entry.paid_amount_cents)),fixedMonthly:Boolean(entry.fixed_monthly),managedByXml:String(entry.operation_key||"").startsWith("FUNRURAL:"),notes:entry.notes,category:{id:entry.category_id,name:entry.category_name},person:entry.person_id?{id:entry.person_id,legalName:entry.legal_name}:null});

export async function generalEntryOptions(){const db=d1();const[categories,people,accounts]=await Promise.all([db.prepare("SELECT id,name,type FROM financial_categories WHERE active=1 ORDER BY name").all(),db.prepare("SELECT id,legal_name legalName FROM people WHERE active=1 ORDER BY legal_name").all(),db.prepare("SELECT id,bank_name bankName,account_number accountNumber FROM bank_accounts WHERE active=1 ORDER BY bank_name,account_number").all()]);return{categories:categories.results,people:people.results,accounts:accounts.results}}

export async function listGeneralEntries(){const result=await d1().prepare("SELECT g.*,c.name category_name,p.legal_name FROM general_entries g JOIN financial_categories c ON c.id=g.category_id LEFT JOIN people p ON p.id=g.person_id WHERE g.active=1 ORDER BY g.due_date").all();return result.results.map(record)}

export async function createGeneralEntry(input:unknown){
 const data=generalEntrySchema.parse(input),db=d1(),stamp=now();
 const duplicate=await db.prepare("SELECT id FROM general_entries WHERE operation_key=?").bind(data.operationKey).first<{id:string}>();if(duplicate)return{id:duplicate.id};
 const count=data.fixedMonthly?12:1,entries=monthlyDueDates(data.dueDate,count).map((dueDate,index)=>({id:id(),dueDate,operationKey:index===0?data.operationKey:`${data.operationKey}:${index+1}`}));
 await db.batch([...entries.map(entry=>db.prepare("INSERT INTO general_entries(id,direction,description,category_id,person_id,due_date,amount_cents,paid_amount_cents,fixed_monthly,operation_key,notes,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,?,?,1,?,?)").bind(entry.id,data.direction,data.description,data.categoryId,optional(data.personId),entry.dueDate,cents(data.amount),bool(data.fixedMonthly),entry.operationKey,optional(data.notes),stamp,stamp)),db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_data,created_at) VALUES(?,'GeneralEntry',?,'CREATE',?,?)").bind(id(),entries[0].id,JSON.stringify({description:data.description,amount:data.amount,months:count}),stamp)]);
 return{id:entries[0].id,created:count};
}

export async function updateGeneralEntry(entryId:string,input:unknown){
 const data=generalEntrySchema.parse(input),db=d1(),current=await db.prepare("SELECT paid_amount_cents,operation_key FROM general_entries WHERE id=? AND active=1").bind(entryId).first<{paid_amount_cents:number;operation_key:string|null}>();
 if(!current)throw new Error("ORIGIN_NOT_FOUND");if(cents(data.amount)<Number(current.paid_amount_cents))throw new Error("INSTALLMENT_BELOW_PAID");const stamp=now();
 if(String(current.operation_key||"").startsWith("FUNRURAL:"))throw new Error("FUNRURAL_ENTRY_MANAGED");
 await db.batch([db.prepare("UPDATE general_entries SET direction=?,description=?,category_id=?,person_id=?,due_date=?,amount_cents=?,fixed_monthly=?,notes=?,updated_at=? WHERE id=?").bind(data.direction,data.description,data.categoryId,optional(data.personId),data.dueDate,cents(data.amount),bool(data.fixedMonthly),optional(data.notes),stamp,entryId),db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,after_data,created_at) VALUES(?,'GeneralEntry',?,'UPDATE',?,?)").bind(id(),entryId,JSON.stringify({description:data.description,amount:data.amount}),stamp)]);return{id:entryId};
}

export async function cancelGeneralEntry(entryId:string){const db=d1(),current=await db.prepare("SELECT paid_amount_cents,operation_key FROM general_entries WHERE id=? AND active=1").bind(entryId).first<{paid_amount_cents:number;operation_key:string|null}>();if(!current)throw new Error("ORIGIN_NOT_FOUND");const operationKey=String(current.operation_key||"");if(operationKey.startsWith("FUNRURAL:"))throw new Error("FUNRURAL_ENTRY_MANAGED");if(Number(current.paid_amount_cents)>0)throw new Error("ENTRY_HAS_SETTLEMENT");const stamp=now(),xmlExpense=operationKey.match(/^XML-EXPENSE:(\d{44}):\d+$/),xmlPrefix=xmlExpense?`XML-EXPENSE:${xmlExpense[1]}:%`:null;const statements=[db.prepare("UPDATE imported_documents SET general_entry_id=NULL,status='REVIEW',updated_at=? WHERE general_entry_id=?").bind(stamp,entryId),db.prepare("UPDATE general_entries SET active=0,updated_at=? WHERE id=?").bind(stamp,entryId)];if(xmlPrefix)statements.push(db.prepare("UPDATE fiscal_documents SET general_entry_id=(SELECT id FROM general_entries WHERE active=1 AND operation_key LIKE ? ORDER BY due_date,id LIMIT 1),status=CASE WHEN EXISTS(SELECT 1 FROM general_entries WHERE active=1 AND operation_key LIKE ?) THEN 'LINKED' ELSE 'PENDING' END,linked_at=CASE WHEN EXISTS(SELECT 1 FROM general_entries WHERE active=1 AND operation_key LIKE ?) THEN linked_at ELSE NULL END,updated_at=? WHERE access_key=?").bind(xmlPrefix,xmlPrefix,xmlPrefix,stamp,xmlExpense![1]));else statements.push(db.prepare("UPDATE fiscal_documents SET general_entry_id=NULL,status='PENDING',linked_at=NULL,updated_at=? WHERE general_entry_id=?").bind(stamp,entryId));statements.push(db.prepare("INSERT INTO audit_logs(id,entity_type,entity_id,action,created_at) VALUES(?,'GeneralEntry',?,'CANCEL',?)").bind(id(),entryId,stamp));await db.batch(statements);return{ok:true}}
