"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CirclePlus, Coffee, Plus, Search, Trash2, X } from "lucide-react";

type Option={id:string;legalName?:string;name?:string}; type Installment={dueDate:string;amount:string};
type Purchase={id:string;sequence:number;businessType:"PURCHASE"|"SALE";date:string;kilograms:string;sacks:string;pricePerSack:string;totalAmount:string;commissionAmount:string;supplier:{legalName:string};broker?:{name:string}|null;installments:{id:string;dueDate:string;amount:string}[]};
const money=(v:number|string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v));
const br=(v:string)=>new Date(v).toLocaleDateString("pt-BR"); const n=(v:string)=>Number(v.replace(/\./g,"").replace(",","."))||0;
const today=()=>new Date().toISOString().slice(0,10);

export function PurchaseWorkspace({options}:{options:{suppliers:Option[];clients:Option[];brokers:Option[]}}){
 const formRef=useRef<HTMLFormElement>(null);
 const [items,setItems]=useState<Purchase[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState("");
 const [form,setForm]=useState({businessType:"PURCHASE",date:today(),supplierId:"",kilograms:"",pricePerSack:"",adjustmentAmount:"0,00",brokerId:"",commissionMode:"PERCENT",commissionValue:"0",notes:""});
 const [parts,setParts]=useState<Installment[]>([{dueDate:today(),amount:""}]);
 const load=useCallback(async()=>{const r=await fetch(`/api/compras?busca=${encodeURIComponent(search)}`);setItems(await r.json())},[search]); useEffect(()=>{let active=true;fetch(`/api/compras?busca=${encodeURIComponent(search)}`).then(r=>r.json()).then(data=>{if(active)setItems(data)});return()=>{active=false}},[search]);
 const sacks=n(form.kilograms)/60,gross=sacks*n(form.pricePerSack),total=gross+n(form.adjustmentAmount),commission=form.commissionMode==="PERCENT"?total*n(form.commissionValue)/100:n(form.commissionValue);
 const partTotal=useMemo(()=>parts.reduce((s,p)=>s+n(p.amount),0),[parts]);
 useEffect(()=>{function saveWithF2(event:KeyboardEvent){if(event.key==="F2"&&open&&!busy){event.preventDefault();formRef.current?.requestSubmit()}}window.addEventListener("keydown",saveWithF2);return()=>window.removeEventListener("keydown",saveWithF2)},[open,busy]);
 function reset(){setForm({businessType:"PURCHASE",date:today(),supplierId:"",kilograms:"",pricePerSack:"",adjustmentAmount:"0,00",brokerId:"",commissionMode:"PERCENT",commissionValue:"0",notes:""});setParts([{dueDate:today(),amount:""}]);setError("")}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/compras",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,installments:parts})});const body=await r.json();setBusy(false);if(!r.ok){setError(body.error||"Não foi possível salvar.");return}setOpen(false);reset();await load()}
 return <div className="page purchases-page"><header className="records-header"><div><span className="eyebrow">Operação de café</span><h1>Negócios de Café</h1><p className="page-subtitle">Compras e vendas em uma única tela, com vencimentos e comissão.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={17}/>Novo negócio</button></header>
 <div className="purchase-summary"><div><small>Compras</small><strong>{items.filter(i=>i.businessType==="PURCHASE").length}</strong></div><div><small>Vendas</small><strong>{items.filter(i=>i.businessType==="SALE").length}</strong></div><div><small>Total de negócios</small><strong>{items.length}</strong></div></div>
 <section className="records-panel"><div className="records-toolbar"><label className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar fornecedor, cliente ou corretor"/></label><span className="record-count">{items.length} negócio(s)</span></div><div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Nº</th><th>Data</th><th>Fornecedor / cliente</th><th>Quilos</th><th>Sacas</th><th>Preço/saca</th><th>Total</th><th>Corretor</th><th>Comissão</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><span className={`business-badge ${i.businessType.toLowerCase()}`}>{i.businessType==="PURCHASE"?"Compra":"Venda"}</span></td><td><strong>{String(i.sequence).padStart(5,"0")}</strong></td><td>{br(i.date)}</td><td><strong>{i.supplier.legalName}</strong></td><td>{Number(i.kilograms).toLocaleString("pt-BR")}</td><td>{Number(i.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3})}</td><td>{money(i.pricePerSack)}</td><td><strong>{money(i.totalAmount)}</strong></td><td>{i.broker?.name||"—"}</td><td>{money(i.commissionAmount)}</td></tr>)}</tbody></table>{!items.length&&<div className="state-box"><span className="empty-icon"><Coffee/></span><strong>Nenhum negócio registrado</strong><p>Crie a primeira compra ou venda para começar.</p></div>}</div></section>
 {open&&<div className="modal-layer purchase-modal-layer"><div className="form-modal purchase-modal"><div className="modal-header"><div><span className="eyebrow">Novo negócio</span><h2>{form.businessType==="PURCHASE"?"Compra":"Venda"} de café</h2></div><button onClick={()=>setOpen(false)}><X/></button></div><form ref={formRef} onSubmit={submit}><div className="modal-body">{error&&<div className="form-error">{error}</div>}
 <fieldset className="form-section"><legend>Dados do negócio</legend><div className="business-toggle"><button type="button" className={form.businessType==="PURCHASE"?"selected":""} onClick={()=>setForm({...form,businessType:"PURCHASE",supplierId:""})}>Compra</button><button type="button" className={form.businessType==="SALE"?"selected sale":""} onClick={()=>setForm({...form,businessType:"SALE",supplierId:""})}>Venda</button></div><div className="form-grid"><label className="field"><span>Data <b>*</b></span><input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="field"><span>{form.businessType==="PURCHASE"?"Fornecedor":"Cliente"} <b>*</b></span><select required value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Selecione</option>{(form.businessType==="PURCHASE"?options.suppliers:options.clients).map(o=><option value={o.id} key={o.id}>{o.legalName}</option>)}</select></label><label className="field"><span>Quantidade em quilos <b>*</b></span><input required inputMode="decimal" value={form.kilograms} onChange={e=>setForm({...form,kilograms:e.target.value})} placeholder="0,000"/></label><label className="field"><span>Preço por saca <b>*</b></span><input required inputMode="decimal" value={form.pricePerSack} onChange={e=>setForm({...form,pricePerSack:e.target.value})} placeholder="0,00"/></label><label className="field"><span>Ajuste (+ ou -)</span><input value={form.adjustmentAmount} onChange={e=>setForm({...form,adjustmentAmount:e.target.value})}/></label><div className="calculated"><small>Sacas calculadas</small><strong>{sacks.toLocaleString("pt-BR",{maximumFractionDigits:3})}</strong></div></div><div className="total-strip"><span>Valor bruto <b>{money(gross)}</b></span><span>Valor final <strong>{money(total)}</strong></span></div></fieldset>
 <fieldset className="form-section"><legend>Corretor e comissão</legend><div className="form-grid"><label className="field"><span>Corretor</span><select value={form.brokerId} onChange={e=>setForm({...form,brokerId:e.target.value})}><option value="">Sem corretor</option>{options.brokers.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label className="field"><span>Forma da comissão</span><select value={form.commissionMode} onChange={e=>setForm({...form,commissionMode:e.target.value})}><option value="PERCENT">Percentual sobre o total (%)</option><option value="AMOUNT">Valor direto em reais (R$)</option></select></label><label className="field"><span>{form.commissionMode==="PERCENT"?"Percentual (%)":"Comissão (R$)"}</span><input value={form.commissionValue} onChange={e=>setForm({...form,commissionValue:e.target.value})}/></label><div className="calculated copper"><small>Comissão calculada</small><strong>{money(commission)}</strong></div></div></fieldset>
 <fieldset className="form-section"><legend>Vencimentos de {form.businessType==="PURCHASE"?"pagamento":"recebimento"}</legend><p>Comece com um vencimento e adicione outros quando precisar.</p><div className="installments">{parts.map((p,index)=><div className="installment-row" key={index}><span>{index+1}</span><label className="field"><small>Data</small><input type="date" required value={p.dueDate} onChange={e=>setParts(parts.map((x,i)=>i===index?{...x,dueDate:e.target.value}:x))}/></label><label className="field"><small>Valor</small><input required value={p.amount} onChange={e=>setParts(parts.map((x,i)=>i===index?{...x,amount:e.target.value}:x))} placeholder="0,00"/></label>{parts.length>1&&<button type="button" onClick={()=>setParts(parts.filter((_,i)=>i!==index))}><Trash2 size={16}/></button>}</div>)}</div><button className="add-installment" type="button" onClick={()=>setParts([...parts,{dueDate:today(),amount:""}])}><CirclePlus size={16}/>Adicionar vencimento</button><div className={`installment-check ${Math.abs(partTotal-total)<.01?"ok":""}`}><span>Soma dos vencimentos: <b>{money(partTotal)}</b></span><span>Diferença: <b>{money(total-partTotal)}</b></span></div></fieldset>
 <fieldset className="form-section"><legend>Observações</legend><label className="field"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></fieldset></div><div className="modal-footer"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?"Salvando...":<>Salvar negócio <kbd>F2</kbd></>}</button></div></form></div></div>}</div>
}
