"use client";
import { useCallback, useEffect, useState } from "react";
import { Printer, RefreshCw } from "lucide-react";
type Option={id:string;legalName:string};
type Row={id:string;sequence:number;date:string;kilograms:string;sacks:string;pricePerSack:string;totalAmount:string;supplier:{legalName:string}};
type Summary={count:number;kilograms:string;sacks:string;amount:string;averagePrice:string};
type Entry={id:string;number:number;amount:string;paidAmount:string;sacks:string|null;pricePerSack:string|null;origin:"CAFE"|"GENERAL";description:string;purchase:{businessType:string;sequence:number;supplier:{legalName:string}}};
type Day={date:string;payable:string;receivable:string;balance:string;cumulative:string;entries:Entry[]};
const money=(v:string|number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v));
const date=(v:string)=>new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("pt-BR");
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`};
const today=()=>new Date().toISOString().slice(0,10);

export function ReportsWorkspace({suppliers,clients}:{suppliers:Option[];clients:Option[]}){
 const[tab,setTab]=useState<"PURCHASE"|"SALE"|"DAILY">("DAILY"),[start,setStart]=useState(monthStart()),[end,setEnd]=useState(today()),[person,setPerson]=useState(""),[direction,setDirection]=useState("ALL"),[rows,setRows]=useState<Row[]>([]),[summary,setSummary]=useState<Summary>({count:0,kilograms:"0",sacks:"0",amount:"0",averagePrice:"0"}),[days,setDays]=useState<Day[]>([]);
 const people=tab==="PURCHASE"?suppliers:tab==="SALE"?clients:[...suppliers,...clients.filter(c=>!suppliers.some(s=>s.id===c.id))];
 const load=useCallback(async()=>{const common=`inicio=${start}&fim=${end}&pessoa=${person}`;if(tab==="DAILY"){setDays(await(await fetch(`/api/relatorios/mapa-diario?${common}&direcao=${direction}`)).json())}else{const b=await(await fetch(`/api/relatorios/negocios?${common}&tipo=${tab}`)).json();setRows(b.rows);setSummary(b.summary)}},[tab,start,end,person,direction]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t)},[load]);
 function change(next:typeof tab){setTab(next);setPerson("")}
 const periodTotals=days.reduce((a,d)=>({payable:a.payable+Number(d.payable),receivable:a.receivable+Number(d.receivable)}),{payable:0,receivable:0});
 return <div className="page reports-page">
  <header className="records-header"><div><span className="eyebrow">Conferência e impressão</span><h1>{tab==="DAILY"?"Mapa diário a pagar e receber":tab==="PURCHASE"?"Relatório de compras":"Relatório de vendas"}</h1><p className="page-subtitle">Café e contas gerais calculados somente no período selecionado.</p></div><button className="secondary-button print-button" onClick={()=>window.print()}><Printer size={16}/>Imprimir</button></header>
  <div className="report-tabs"><button className={tab==="DAILY"?"active":""} onClick={()=>change("DAILY")}>Mapa diário</button><button className={tab==="PURCHASE"?"active":""} onClick={()=>change("PURCHASE")}>Compras</button><button className={tab==="SALE"?"active":""} onClick={()=>change("SALE")}>Vendas</button></div>
  <section className="report-filters"><label className="field"><span>Data inicial</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field"><span>Data final</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field"><span>{tab==="PURCHASE"?"Fornecedor":tab==="SALE"?"Cliente":"Fornecedor ou cliente"}</span><select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Todos</option>{people.map(p=><option value={p.id} key={p.id}>{p.legalName}</option>)}</select></label>{tab==="DAILY"&&<label className="field"><span>Mostrar</span><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="ALL">Pagar e receber</option><option value="PAYABLE">Somente a pagar</option><option value="RECEIVABLE">Somente a receber</option></select></label>}<button className="secondary-button" onClick={()=>void load()}><RefreshCw size={15}/>Atualizar</button></section>
  {tab!=="DAILY"?<><div className="report-totals"><div><small>Lançamentos</small><strong>{summary.count}</strong></div><div><small>Quilos</small><strong>{Number(summary.kilograms).toLocaleString("pt-BR")}</strong></div><div><small>Sacas</small><strong>{Number(summary.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3})}</strong></div><div><small>Valor total</small><strong>{money(summary.amount)}</strong></div><div><small>Preço médio ponderado</small><strong>{money(summary.averagePrice)}</strong></div></div><section className="records-panel"><div className="table-wrap"><table><thead><tr><th>Data</th><th>Negócio</th><th>{tab==="PURCHASE"?"Fornecedor":"Cliente"}</th><th>Quilos</th><th>Sacas</th><th>Preço unitário</th><th>Valor total</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.date)}</td><td>{String(r.sequence).padStart(5,"0")}</td><td><strong>{r.supplier.legalName}</strong></td><td>{Number(r.kilograms).toLocaleString("pt-BR")}</td><td>{Number(r.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3})}</td><td>{money(r.pricePerSack)}</td><td><strong>{money(r.totalAmount)}</strong></td></tr>)}</tbody></table></div></section></>:
  <section className="daily-map">{days.map(d=><article key={d.date}><div className="daily-date"><strong>{date(d.date)}</strong></div><table><thead><tr><th>Origem</th><th>Tipo</th><th>Negócio / descrição</th><th>Fornecedor / cliente</th><th>Sacas</th><th>Preço/saca</th><th>Parcela</th><th>Valor em aberto</th></tr></thead><tbody>{d.entries.map(e=><tr key={e.id}><td>{e.origin==="CAFE"?"Café":"Conta geral"}</td><td>{e.purchase.businessType==="PURCHASE"?"A pagar":"A receber"}</td><td>{e.origin==="CAFE"?String(e.purchase.sequence).padStart(5,"0"):e.description}</td><td>{e.purchase.supplier.legalName}</td><td>{e.sacks?Number(e.sacks).toLocaleString("pt-BR",{maximumFractionDigits:3}):"—"}</td><td>{e.pricePerSack?money(e.pricePerSack):"—"}</td><td>{e.origin==="CAFE"?e.number:"—"}</td><td><strong>{money(Number(e.amount)-Number(e.paidAmount))}</strong></td></tr>)}</tbody><tfoot><tr><td colSpan={4}><strong>Total de {date(d.date)}</strong></td><td colSpan={2}>A pagar: <b>{money(d.payable)}</b></td><td>A receber: <b>{money(d.receivable)}</b></td><td>Saldo: <b>{money(d.balance)}</b></td></tr></tfoot></table></article>)}{days.length>0&&<div className="period-total"><span>Total a pagar <b>{money(periodTotals.payable)}</b></span><span>Total a receber <b>{money(periodTotals.receivable)}</b></span><span>Saldo do período <b>{money(periodTotals.receivable-periodTotals.payable)}</b></span></div>}{!days.length&&<div className="state-box"><strong>Nenhum vencimento no período</strong><p>Altere as datas ou os filtros para consultar o mapa diário.</p></div>}</section>}
 </div>
}
